config/routes.rb
Rails.application.routes.draw do
  resources :nurses
  resources :receptions
  resources :hospitals
  resources :appointments
  resources :physicians
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "hospitals#index"
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :patients, through: :appointments
    belongs_to :hospital

    end
    
   

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: %i[ show edit update destroy ]

  # GET /physicians or /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1 or /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
    @hospitals = Hospital.all
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians or /physicians.json
  def create
    @physician = Physician.new(physician_params)
    @physician.hospital = Hospital.find(params[:physician][:hospital_id])

    respond_to do |format|
      if @physician.save
        format.html { redirect_to physician_url(@physician), notice: "Physician was successfully created." }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1 or /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to physician_url(@physician), notice: "Physician was successfully updated." }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1 or /physicians/1.json
  def destroy
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to physicians_url, notice: "Physician was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def physician_params
      params.require(:physician).permit(:name)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_with(model: physician) do |form| %>
  <% if physician.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
        <% physician.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
  <%= form.label :hospital_id, style: "display: block" %>
  <%= form.collection_select :hospital_id, Hospital.all, :id, :name, {}, { class: 'form-control' } %>
</div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/physicians/_physician.html.erb
<div id="<%= dom_id physician %>">
  <p>
    <strong>Name:</strong>
    <%= physician.name %>
  </p>

</div>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render "form", physician: @physician %>

<br>

<div>
  <%= link_to "Show this physician", @physician %> |
  <%= link_to "Back to physicians", physicians_path %>
</div>

app/views/physicians/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Physicians</h1>

<div id="physicians">
  <% @physicians.each do |physician| %>
    <%= render physician %>
    <p>
      <%= link_to "Show this physician", physician %>
    </p>
  <% end %>
</div>

<%= link_to "New physician", new_physician_path %>

app/views/physicians/new.html.erb
<h1>New physician</h1>

<%= render "form", physician: @physician %>

<br>

<div>
  <%= link_to "Back to physicians", physicians_path %>
</div>

app/views/physicians/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @physician %>

<div>
  <%= link_to "Edit this physician", edit_physician_path(@physician) %> |
  <%= link_to "Back to physicians", physicians_path %>

  <%= button_to "Destroy this physician", @physician, method: :delete %>
</div>