config/routes.rb
Rails.application.routes.draw do
  resources :nurses
  resources :receptions
  resources :hospitals
  resources :appointments
  resources :physicians
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "hospitals#index"
end

app/models/reception.rb
class Reception < ApplicationRecord
    belongs_to :hospital
    validates :name, presence: true
end

app/controllers/receptions_controller.rb
class ReceptionsController < ApplicationController
  before_action :set_reception, only: %i[ show edit update destroy ]

  # GET /receptions or /receptions.json
  def index
    @receptions = Reception.all
  end

  # GET /receptions/1 or /receptions/1.json
  def show
  end

  # GET /receptions/new
  def new
    @reception = Reception.new
    @hospitals = Hospital.all
  
  end

  # GET /receptions/1/edit
  def edit
  end

  # POST /receptions or /receptions.json
  def create
    @reception = Reception.new(reception_params)
    @reception.hospital = Hospital.find(params[:reception][:hospital_id])
   


    respond_to do |format|
      if @reception.save
        format.html { redirect_to reception_url(@reception), notice: "Reception was successfully created." }
        format.json { render :show, status: :created, location: @reception }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reception.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receptions/1 or /receptions/1.json
  def update
    respond_to do |format|
      if @reception.update(reception_params)
        format.html { redirect_to reception_url(@reception), notice: "Reception was successfully updated." }
        format.json { render :show, status: :ok, location: @reception }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reception.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receptions/1 or /receptions/1.json
  def destroy
    @reception.destroy

    respond_to do |format|
      format.html { redirect_to receptions_url, notice: "Reception was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reception
      @reception = Reception.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reception_params
      params.require(:reception).permit(:name, :phone_number)
    end
end

app/helpers/receptions_helper.rb
module ReceptionsHelper
end

app/views/receptions/_form.html.erb
<%= form_with(model: reception) do |form| %>
  <% if reception.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reception.errors.count, "error") %> prohibited this reception from being saved:</h2>

      <ul>
        <% reception.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>
  <div>
  <%= form.label :hospital_id, style: "display: block" %>
  <%= form.collection_select :hospital_id, Hospital.all, :id, :name, {}, { class: 'form-control' } %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/receptions/_reception.html.erb
<div id="<%= dom_id reception %>">
  <p>
    <strong>Name:</strong>
    <%= reception.name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= reception.phone_number %>
  </p>
  <p>
  <strong>Hospital :</strong>
  <%= reception.hospital.name %>
</p>

</div>

app/views/receptions/edit.html.erb
<h1>Editing reception</h1>

<%= render "form", reception: @reception %>

<br>

<div>
  <%= link_to "Show this reception", @reception %> |
  <%= link_to "Back to receptions", receptions_path %>
</div>

app/views/receptions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Receptions</h1>

<div id="receptions">
  <% @receptions.each do |reception| %>
    <%= render reception %>
    <p>
      <%= link_to "Show this reception", reception %>
    </p>
  <% end %>
</div>

<%= link_to "New reception", new_reception_path %>

app/views/receptions/new.html.erb
<h1>New reception</h1>

<%= render "form", reception: @reception %>

<br>

<div>
  <%= link_to "Back to receptions", receptions_path %>
</div>

app/views/receptions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reception %>

<div>
  <%= link_to "Edit this reception", edit_reception_path(@reception) %> |
  <%= link_to "Back to receptions", receptions_path %>

  <%= button_to "Destroy this reception", @reception, method: :delete %>
</div>