config/routes.rb
Rails.application.routes.draw do
  resources :nurses
  resources :receptions
  resources :hospitals
  resources :appointments
  resources :physicians
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "hospitals#index"
end

app/models/hospital.rb
class Hospital < ApplicationRecord
    has_many :patients, dependent: :destroy
    has_many :physicians, dependent: :destroy
    has_one  :reception
    has_and_belongs_to_many :nurses, dependent: :destroy
    validates :name, presence: true
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: %i[ show edit update destroy ]

  # GET /hospitals or /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1 or /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals or /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to hospital_url(@hospital), notice: "Hospital was successfully created." }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1 or /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to hospital_url(@hospital), notice: "Hospital was successfully updated." }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1 or /hospitals/1.json
  def destroy
    @hospital.destroy

    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: "Hospital was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hospital_params
      params.require(:hospital).permit(:name)
    end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital) do |form| %>
  <% if hospital.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
        <% hospital.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitals/_hospital.html.erb
<div id="<%= dom_id hospital %>">
  <p>
    <strong>Name:</strong>
    <%= hospital.name %>
  </p>

</div>

app/views/hospitals/edit.html.erb
<h1>Editing hospital</h1>

<%= render "form", hospital: @hospital %>

<br>

<div>
  <%= link_to "Show this hospital", @hospital %> |
  <%= link_to "Back to hospitals", hospitals_path %>
</div>

app/views/hospitals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hospitals</h1>

<div id="hospitals">
  <% @hospitals.each do |hospital| %>
    <%= render hospital %>
    <p>
      <%= link_to "Show this hospital", hospital %>
    </p>
  <% end %>
</div>

<%= link_to "New hospital", new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New hospital</h1>

<%= render "form", hospital: @hospital %>

<br>

<div>
  <%= link_to "Back to hospitals", hospitals_path %>
</div>

app/views/hospitals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hospital %>

<div>
  <%= link_to "Edit this hospital", edit_hospital_path(@hospital) %> |
  <%= link_to "Back to hospitals", hospitals_path %>

  <%= button_to "Destroy this hospital", @hospital, method: :delete %>
</div>